version: '3.7'

services:

  app:
    container_name: nestjs-app
    restart: always
    build:
      context: .
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    command: npm run start:dev
    env_file:
      - .env
    ports:
      - "3000:3000"
    expose:
      - "3000"
    depends_on:
      - mysql_db
    networks:
      - short_network
  
  mysql_db:
    container_name: mysql_db
    image: mysql:5.7
    restart: always
    env_file: ./.env
    environment:
      - MYSQL_DATABASE=shortlink
      - MYSQL_ROOT_PASSWORD=root
    ports:
    - 3306:3306
    volumes:
      - ./mysql:/var/lib/mysql
      - ./mysql/init:/docker-entrypoint-initdb.d/:ro
    networks:
      - short_network

networks:
  short_network: